export const FETCH_QUIZ_REQUEST = 'FETCH_QUIZ_REQUEST';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_FAILURE = 'FETCH_QUIZ_FAILURE';
export const SELECT_TAG = 'SELECT_TAG';
export const SELECT_ANSWER = 'SELECT_ANSWER';
export const ADD_SCORE = 'ADD_SCORE';

